// generated by go run gen.go; DO NOT EDIT

// Package roboto provides the "Roboto" TrueType font
package roboto

import _ "embed"

//go:embed ttfs/Roboto-Light.ttf
var RobotoLight []byte

//go:embed ttfs/Roboto-Thin.ttf
var RobotoThin []byte

//go:embed ttfs/Roboto-MediumItalic.ttf
var RobotoMediumItalic []byte

//go:embed ttfs/Roboto-BlackItalic.ttf
var RobotoBlackItalic []byte

//go:embed ttfs/Roboto-ThinItalic.ttf
var RobotoThinItalic []byte

//go:embed ttfs/Roboto-Medium.ttf
var RobotoMedium []byte

//go:embed ttfs/Roboto-LightItalic.ttf
var RobotoLightItalic []byte

//go:embed ttfs/Roboto-BoldItalic.ttf
var RobotoBoldItalic []byte

//go:embed ttfs/Roboto-Regular.ttf
var RobotoRegular []byte

//go:embed ttfs/Roboto-Italic.ttf
var RobotoItalic []byte

//go:embed ttfs/Roboto-Bold.ttf
var RobotoBold []byte

//go:embed ttfs/Roboto-Black.ttf
var RobotoBlack []byte
